-- table
CREATE TABLE questions (
    id SERIAL PRIMARY KEY,
    question TEXT NOT NULL CHECK (length(question) <= 200),
    date_added TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    date_posted DATE
);

-- questions
INSERT INTO questions (question) VALUES
('What''s your favourite 80s film?'),
('What''s your favourite accent?'),
('What''s your favourite adjective?'),
('What''s your favourite age?'),
('What''s your favourite album from the 90s?'),
('What''s your favourite animal?'),
('What''s your favourite argument?'),
('What''s your favourite Arnie film?'),
('What''s your favourite bacon?'),
('What''s your favourite band?'),
('What''s your favourite battle?'),
('What''s your favourite bean?'),
('What''s your favourite bed?'),
('What''s your favourite beer?'),
('What''s your favourite belief?'),
('What''s your favourite bird?'),
('What''s your favourite biscuit?'),
('What''s your favourite blind?'),
('What''s your favourite body part?'),
('What''s your favourite bonus?'),
('What''s your favourite bottle?'),
('What''s your favourite box?'),
('What''s your favourite brand?'),
('What''s your favourite break?'),
('What''s your favourite breed of cow?'),
('What''s your favourite breed of dog?'),
('What''s your favourite budget supermarket?'),
('What''s your favourite bug?'),
('What''s your favourite cake?'),
('What''s your favourite cartoon?'),
('What''s your favourite cat?'),
('What''s your favourite catchphrase?'),
('What''s your favourite celebrity?'),
('What''s your favourite cephalopod?'),
('What''s your favourite cereal?'),
('What''s your favourite chain?'),
('What''s your favourite chair?'),
('What''s your favourite character?'),
('What''s your favourite charger?'),
('What''s your favourite charity?'),
('What''s your favourite cheek?'),
('What''s your favourite cheese joke?'),
('What''s your favourite cheese?'),
('What''s your favourite chord?'),
('What''s your favourite city?'),
('What''s your favourite cliche?'),
('What''s your favourite clock?'),
('What''s your favourite cloud?'),
('What''s your favourite club?'),
('What''s your favourite collective noun?'),
('What''s your favourite colour?'),
('What''s your favourite comic?'),
('What''s your favourite condiment?'),
('What''s your favourite controversial subject?'),
('What''s your favourite core?'),
('What''s your favourite country that begins with the letter B?'),
('What''s your favourite county?'),
('What''s your favourite cover?'),
('What''s your favourite cowboy name?'),
('What''s your favourite crisp?'),
('What''s your favourite curry?'),
('What''s your favourite danger?'),
('What''s your favourite day?'),
('What''s your favourite defence?'),
('What''s your favourite degree?'),
('What''s your favourite dinosaur?'),
('What''s your favourite disease?'),
('What''s your favourite door?'),
('What''s your favourite dragon?'),
('What''s your favourite drink?'),
('What''s your favourite drop?'),
('What''s your favourite duck joke?'),
('What''s your favourite Eddie Murphy film?'),
('What''s your favourite egg?'),
('What''s your favourite emoticon?'),
('What''s your favourite end-of-the-world scenario?'),
('What''s your favourite error?'),
('What''s your favourite excuse?'),
('What''s your favourite extinct species?'),
('What''s your favourite face?'),
('What''s your favourite feeling?'),
('What''s your favourite film?'),
('What''s your favourite finishing move?'),
('What''s your favourite fish?'),
('What''s your favourite five-syllable word?'),
('What''s your favourite flap?'),
('What''s your favourite flavour Fruit Pastel?'),
('What''s your favourite football team?'),
('What''s your favourite forest?'),
('What''s your favourite French word?'),
('What''s your favourite fruit?'),
('What''s your favourite furry animal?'),
('What''s your favourite gap?'),
('What''s your favourite German word?'),
('What''s your favourite ghost?'),
('What''s your favourite glue?'),
('What''s your favourite Guinness world record?'),
('What''s your favourite handle?'),
('What''s your favourite hat?'),
('What''s your favourite head wear?'),
('What''s your favourite high?'),
('What''s your favourite highlighter pen?'),
('What''s your favourite holiday destination?'),
('What''s your favourite horse?'),
('What''s your favourite inanimate object?'),
('What''s your favourite Indian dish?'),
('What''s your favourite item of clothing?'),
('What''s your favourite item of formal clothing?'),
('What''s your favourite job?'),
('What''s your favourite key?'),
('What''s your favourite keyboard shortcut?'),
('What''s your favourite kind of light?'),
('What''s your favourite kind of sauce?'),
('What''s your favourite knot?'),
('What''s your favourite language?'),
('What''s your favourite letter?'),
('What''s your favourite lie?'),
('What''s your favourite line?'),
('What''s your favourite link?'),
('What''s your favourite lyric?'),
('What''s your favourite made up fact?'),
('What''s your favourite measure?'),
('What''s your favourite meme?'),
('What''s your favourite method of transport?'),
('What''s your favourite Michael J Fox film?'),
('What''s your favourite mistake?'),
('What''s your favourite moon?'),
('What''s your favourite museum?'),
('What''s your favourite mustache?'),
('What''s your favourite naughty word?'),
('What''s your favourite neckline?'),
('What''s your favourite need?'),
('What''s your favourite news?'),
('What''s your favourite number?'),
('What''s your favourite nut?'),
('What''s your favourite one-syllable word?'),
('What''s your favourite onomatopoeic word?'),
('What''s your favourite organ?'),
('What''s your favourite paint?'),
('What''s your favourite painting?'),
('What''s your favourite pan?'),
('What''s your favourite paper?'),
('What''s your favourite part of a pig?'),
('What''s your favourite party?'),
('What''s your favourite paste?'),
('What''s your favourite pattern?'),
('What''s your favourite pen?'),
('What''s your favourite piece of electrical equipment?'),
('What''s your favourite pill?'),
('What''s your favourite planet?'),
('What''s your favourite plant?'),
('What''s your favourite pole?'),
('What''s your favourite Police Academy film?'),
('What''s your favourite portmanteau?'),
('What''s your favourite pound?'),
('What''s your favourite power?'),
('What''s your favourite prescription drug?'),
('What''s your favourite pub?'),
('What''s your favourite punctuation mark?'),
('What''s your favourite radio station?'),
('What''s your favourite rain?'),
('What''s your favourite reptile?'),
('What''s your favourite rhetorical question?'),
('What''s your favourite Rick Moranis film?'),
('What''s your favourite rim?'),
('What''s your favourite rise?'),
('What''s your favourite road?'),
('What''s your favourite roof covering?'),
('What''s your favourite rope?'),
('What''s your favourite rule?'),
('What''s your favourite sausage?'),
('What''s your favourite school?'),
('What''s your favourite screen?'),
('What''s your favourite secret?'),
('What''s your favourite semi-aquatic egg-laying mammal?'),
('What''s your favourite service?'),
('What''s your favourite shellfish?'),
('What''s your favourite shop?'),
('What''s your favourite shower?'),
('What''s your favourite side?'),
('What''s your favourite size of envelope?'),
('What''s your favourite size?'),
('What''s your favourite song?'),
('What''s your favourite sound?'),
('What''s your favourite soup?'),
('What''s your favourite source of existential angst?'),
('What''s your favourite space?'),
('What''s your favourite speling mistaek?'),
('What''s your favourite spin?'),
('What''s your favourite spirit?'),
('What''s your favourite spoonerism?'),
('What''s your favourite star?'),
('What''s your favourite station?'),
('What''s your favourite stew?'),
('What''s your favourite story?'),
('What''s your favourite superlative?'),
('What''s your favourite team?'),
('What''s your favourite thing to do just before you go to sleep?'),
('What''s your favourite tool?'),
('What''s your favourite Tube stop?'),
('What''s your favourite type of heavy metal?'),
('What''s your favourite unit of measurement?'),
('What''s your favourite university?'),
('What''s your favourite vegetable?'),
('What''s your favourite war?'),
('What''s your favourite way to cause pain?'),
('What''s your favourite weed?'),
('What''s your favourite wind?'),
('What''s your favourite window?'),
('What''s your favourite wire?'),
('What''s your favourite word for someone who''s behaving a bit unpredictably?'),
('What''s your favourite word?'),
('What''s your favourite worm?'),
('When''s your favourite time?'),
('Who''s your favourite Akabusi?'),
('Who''s your favourite alien?'),
('Who''s your favourite animal?'),
('Who''s your favourite archer?'),
('Who''s your favourite artist?'),
('Who''s your favourite bearded gentleman?'),
('Who''s your favourite blind person?'),
('Who''s your favourite Booth?'),
('Who''s your favourite Boris?'),
('Who''s your favourite British Prime Minister from the 19th Century?'),
('Who''s your favourite captain?'),
('Who''s your favourite celebrity?'),
('Who''s your favourite character from Neighbours?'),
('Who''s your favourite Charles?'),
('Who''s your favourite Chris?'),
('Who''s your favourite Collins?'),
('Who''s your favourite comedian?'),
('Who''s your favourite Daniel?'),
('Who''s your favourite Darren?'),
('Who''s your favourite deity?'),
('Who''s your favourite designer?'),
('Who''s your favourite developer?'),
('Who''s your favourite dictator?'),
('Who''s your favourite Disney character?'),
('Who''s your favourite DJ?'),
('Who''s your favourite doctor?'),
('Who''s your favourite duck?'),
('Who''s your favourite Ed?'),
('Who''s your favourite ex?'),
('Who''s your favourite explorer?'),
('Who''s your favourite fatty?'),
('Who''s your favourite fish?'),
('Who''s your favourite foot?'),
('Who''s your favourite game show host?'),
('Who''s your favourite geek?'),
('Who''s your favourite German?'),
('Who''s your favourite giant?'),
('Who''s your favourite ginger?'),
('Who''s your favourite hacker?'),
('Who''s your favourite hero?'),
('Who''s your favourite hipster?'),
('Who''s your favourite idiot?'),
('Who''s your favourite inanimate object?'),
('Who''s your favourite Jackson?'),
('Who''s your favourite James?'),
('Who''s your favourite king?'),
('Who''s your favourite lady?'),
('Who''s your favourite lord?'),
('Who''s your favourite maiden?'),
('Who''s your favourite man?'),
('Who''s your favourite manager?'),
('Who''s your favourite mass murderer?'),
('Who''s your favourite Mike?'),
('Who''s your favourite mum?'),
('Who''s your favourite Nelson?'),
('Who''s your favourite news presenter?'),
('Who''s your favourite person from Essex?'),
('Who''s your favourite person from the 80s?'),
('Who''s your favourite person with sideburns?'),
('Who''s your favourite Pete?'),
('Who''s your favourite prince?'),
('Who''s your favourite queen?'),
('Who''s your favourite scientist?'),
('Who''s your favourite Smith?'),
('Who''s your favourite sports personality?'),
('Who''s your favourite star wars character?'),
('Who''s your favourite Trevor?'),
('Who''s your favourite valentine?'),
('Who''s your favourite Viking?'),
('Who''s your favourite weblebrity?'),
('Who''s your favourite wrestler?'),
('Who''s your favourite Wu-Tang member?');
